language: node_js # also works in browsers, but simpler to test in node
node_js:
  - "4"
before_script:
  - ./build.py
script:
  - node ./output/test-tz-node.js

# Use newer distribution that default (precise) to get a newer system
# date command.  See comments in build-tests.py about America/Godthab.
#
# See https://docs.travis-ci.com/user/trusty-ci-environment
dist: trusty
sudo: false
